logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0Cg====
  expiration:
    reset-password: 600000
    default: 7200000

front:
  host: localhost
  port: 3000
