logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/exchange
    username: exchange
    password: exchange
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: nadir976@yandex.ru
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0Cg====
  expiration: 7200000

server:
  host: localhost
  port: 8080
